updated actions

diff --git a/.github/workflows/aws.yml b/.github/workflows/aws.yml
--- a/.github/workflows/aws.yml
+++ b/.github/workflows/aws.yml
@@ -1,10 +1,8 @@
-name: 'Terraform Pipeline'
-
+name: Terraform Deployment
 on:
   push:
-    branches: [ "main" ]
-  pull_request:
-    branches: [ "main" ]
+    branches:
+      - main
   workflow_dispatch:
     inputs:
       aws_service:
@@ -13,56 +11,50 @@ on:
         default: 's3'
         type: choice
         options:
-          - s3
-          - vpc
-          - ec2_linux
-          - ec2_windows
-          - mysql
-          - lambda
-          - k8
+          - 's3'
+          - 'vpc'
+          - 'ec2_linux'
+          - 'ec2_windows'
+          - 'mysql'
+          - 'lambda'
+          - 'k8'
       function:
         description: 'Select function'
         required: true
         default: 'plan'
         type: choice
         options:
-          - plan
-          - apply -auto-approve
-          - destroy -auto-approve
-          - refresh
-
-permissions:
-  contents: read
-
+          - 'plan'
+          - 'apply -auto-approve'
+          - 'destroy -auto-approve'
+          - 'refresh'
 jobs:
-  terraform:
-    name: 'Terraform'
+  build:
     runs-on: ubuntu-latest
-    environment: production
-
     steps:
-    - name: Checkout
-      uses: actions/checkout@v4
-
-    - name: Setup Terraform
-      uses: hashicorp/setup-terraform@v1
-      with:
-        terraform_version: 1.2.3
-
-    - name: Debug Inputs
-      run: |
-        echo "AWS_SERVICE: ${{ github.event.inputs.aws_service }}"
-        echo "FUNCTION: ${{ github.event.inputs.function }}"
-
-    - name: Terraform Init
-      run: terraform init
-
-    - name: Terraform Format
-      run: terraform fmt -check
-
-    - name: Terraform Plan
-      run: terraform plan -input=false
-
-    - name: Terraform Apply
-      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
-      run: terraform apply -auto-approve -input=false
+      - name: Checkout repository
+        uses: actions/checkout@v4
+      - name: Set up Terraform
+        uses: hashicorp/setup-terraform@v3
+        with:
+          terraform_version: 1.4.0
+      - name: Terraform Init, Validate, and Execute
+        env:
+          AWS_SERVICE: ${{ github.event.inputs.aws_service || 's3' }}
+          FUNCTION: ${{ github.event.inputs.function || 'plan' }}
+          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
+          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+        run: |
+          case $AWS_SERVICE in
+            ec2_linux|ec2_windows|vpc|s3|mysql|lambda|k8)
+              echo "Running on $AWS_SERVICE"
+              cd env/$AWS_SERVICE
+              terraform init -reconfigure
+              terraform validate
+              terraform $FUNCTION
+              ;;
+            *)
+              echo "Invalid AWS service selected"
+              exit 1
+              ;;
+          esac
